#!/usr/bin/env bash
if [ $# -eq 0 ] || [ $# -eq 1 ]
then
  echo "Usage: lofa SOURCE OUTPUT"
  echo
  echo "SOURCE: The folder extracted from a docx archive"
  echo "        (i.e. bla.docx --rename--> bla.zip --extract--> bla/)"
  echo
  echo "OUTPUT: name of the OUTPUT file"
  echo "        (.. will be added in front of it automatically,"
  echo "         because I was lazy, this script wasn't the most"
  echo "         important thing, I was young and I needed the money."
  exit 1
fi

pushd $1

outFile="../"$2
if [ -e $outFile ]; then outFile=$outFile"$(date +%Y_%m_%d-%H_%M_%S)"; fi
Q='"'

echo "var z = new JSZip();" >> $outFile

while read path
do
  if [ "$path" = "./word/document.xml" ]; then continue; fi
  IFS='/' read -ra arr <<< $path
  unset IFS
  if [ -f $path ]
  then
    zip="z"
    for i in "${arr[@]}"
    do
      if [ "$i" = "." ]; then continue; fi
      if [ "$i" = "${arr[-1]}" ]
      then
        b64=$(base64 -w0 $path)
        zip="$zip"".file("$Q"$i"$Q","$Q"$b64"$Q", {base64: true});"
      else
        zip=$zip".folder($Q"$i"$Q)"
      fi
    done
  fi
  echo -e $zip$'\n' >> $outFile
done <<< "$(find .)"
popd
# To make the JSZip object quickly downloadable from the browser console:
# z.generateAsync({type:"blob"}).then(function(blob) { saveAs(blob, "hello.docx") });
